const API_BASE_URL = "http://localhost/8080/api/v1";
const MAX_ITEMS_PER_PAGE = 20;
const DEFAULT_LANGUAGE = "en";

const MIN_NAME_LENGTH = 2;
const MAX_NAME_LENGTH = 50;

const MIN_PASSWORD_LENGTH = 8;
const MAX_PASSWORD_LENGTH = 50;

export {
  API_BASE_URL,
  MAX_ITEMS_PER_PAGE,
  DEFAULT_LANGUAGE,
  MIN_NAME_LENGTH,
  MAX_NAME_LENGTH,
  MIN_PASSWORD_LENGTH,
  MAX_PASSWORD_LENGTH,
};
